services:
  mongodb:
    image: mongo:7
    container_name: solee-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: solee
      MONGO_INITDB_ROOT_PASSWORD: solee_secret
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: solee-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: solee-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: solee
      RABBITMQ_DEFAULT_PASS: solee_secret

volumes:
  mongo_data:
